version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: secretary
      POSTGRES_DB: secretary
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/secretary-manager/backend

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/secretary-manager/frontend